from __future__ import annotations

from enum import Enum


class WebhookEventType(str, Enum):
    APPLICATION_STARTUP = "APPLICATION_STARTUP"
    QRCODE_UPDATED = "QRCODE_UPDATED"
    MESSAGES_SET = "MESSAGES_SET"
    MESSAGES_UPSERT = "MESSAGES_UPSERT"
    MESSAGES_UPDATE = "MESSAGES_UPDATE"
    MESSAGES_DELETE = "MESSAGES_DELETE"
    SEND_MESSAGE = "SEND_MESSAGE"
    CONTACTS_SET = "CONTACTS_SET"
    CONTACTS_UPSERT = "CONTACTS_UPSERT"
    CONTACTS_UPDATE = "CONTACTS_UPDATE"
    PRESENCE_UPDATE = "PRESENCE_UPDATE"
    CHATS_SET = "CHATS_SET"
    CHATS_UPSERT = "CHATS_UPSERT"
    CHATS_UPDATE = "CHATS_UPDATE"
    CHATS_DELETE = "CHATS_DELETE"
    GROUPS_UPSERT = "GROUPS_UPSERT"
    GROUP_UPDATE = "GROUP_UPDATE"
    GROUP_PARTICIPANTS_UPDATE = "GROUP_PARTICIPANTS_UPDATE"
    CONNECTION_UPDATE = "CONNECTION_UPDATE"
    CALL = "CALL"
    NEW_JWT_TOKEN = "NEW_JWT_TOKEN"
    TYPEBOT_START = "TYPEBOT_START"
    TYPEBOT_CHANGE_STATUS = "TYPEBOT_CHANGE_STATUS"

    @classmethod
    def from_raw(cls, value: str) -> "WebhookEventType | None":
        try:
            return cls(value)
        except ValueError:
            return None
